# helm/microservices/templates/reward-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rewardService.name }}
spec:
  replicas: {{ .Values.rewardService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.rewardService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rewardService.name }}
    spec:
      containers:
        - name: {{ .Values.rewardService.name }}
          image: "{{ .Values.rewardService.image.repository }}:{{ .Values.rewardService.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: JWT_SECRET