# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: agri-sync
type: Opaque
data:
  DB_USER: {{ .Values.database.user | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc }}