apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
  selector:
    app: {{ .Values.gateway.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
    - port: {{ .Values.userService.service.port }}
      targetPort: 5000
  selector:
    app: {{ .Values.userService.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rewardService.name }}
spec:
  type: {{ .Values.rewardService.service.type }}
  ports:
    - port: {{ .Values.rewardService.service.port }}
      targetPort: 5000
  selector:
    app: {{ .Values.rewardService.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pricePredictionService.name }}
spec:
  type: {{ .Values.pricePredictionService.service.type }}
  ports:
    - port: {{ .Values.pricePredictionService.service.port }}
      targetPort: 5000
  selector:
    app: {{ .Values.pricePredictionService.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ .Values.frontend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userinter.name }}
spec:
  type: {{ .Values.userinter.service.type }}
  ports:
    - port: {{ .Values.userinter.service.port }}
      targetPort: {{ .Values.userinter.service.targetPort }}
      nodePort: {{ .Values.userinter.service.nodePort }}
  selector:
    app: {{ .Values.userinter.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatbot.name }}
spec:
  type: {{ .Values.chatbot.service.type }}
  ports:
    - port: {{ .Values.chatbot.service.port }}
      targetPort: {{ .Values.chatbot.service.targetPort }}
      nodePort: {{ .Values.chatbot.service.nodePort }}
  selector:
    app: {{ .Values.chatbot.name }}
