# helm/microservices/templates/user-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .Values.userService.name }}
spec:
 replicas: {{ .Values.userService.replicaCount }}
 selector:
   matchLabels:
     app: {{ .Values.userService.name }}
 template:
   metadata:
     labels:
       app: {{ .Values.userService.name }}
   spec:
     containers:
       - name: {{ .Values.userService.name }}
         image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
         ports:
           - containerPort: 5000
         env:
           - name: PORT
             value: "5000"
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: DB_HOST
           - name: DB_PORT
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: DB_PORT
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: DB_NAME
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: DB_USER
           - name: DB_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: DB_PASSWORD
           - name: JWT_SECRET
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: JWT_SECRET
           - name: JWT_EXPIRES_IN
             valueFrom:
               secretKeyRef:
                 name: db-credentials
                 key: JWT_EXPIRES_IN