database:
  user:
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: DB_USER
  password:
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: DB_PASSWORD
jwt:
  secret:
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: JWT_SECRET