global:
  environment: development

gateway:
  name: api-gateway
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    # type: LoadBalancer  # Original LoadBalancer type (commented) for cloud deployments
    # port: 80            # Original LoadBalancer port (commented)
    # targetPort: 3000    # Original LoadBalancer targetPort (commented)
    type: NodePort        # Using NodePort for Minikube
    port: 80              # The port for the service
    targetPort: 3000      # Target port inside the container
    nodePort: 31000       # Optional: Specify NodePort (30000-32767 range)

userService:
  name: user-service
  replicaCount: 2
  image:
    repository: gihaa/as-user-service
    tag: latest
  service:
    type: ClusterIP
    port: 5000

rewardService:
  name: reward-service
  replicaCount: 1
  image:
    repository: gihaa/as-reward-service
    tag: latest
  service:
    type: ClusterIP
    port: 5000

pricePredictionService:
  name: price-prediction-service
  replicaCount: 1
  image:
    repository: gihaa/as-price-prediction-service
    tag: latest
  service:
    type: ClusterIP
    port: 5000

database:
  user: "avnadmin"
  password: "AVNS_lP0uW9A3_MC4As3h-NL"
  host: "pg-122ba407-gihansudeeparandimal-f684.g.aivencloud.com"
  port: "17670"
  name: "defaultdb"

jwt:
  secret: "your_jwt_secret"
  expiresIn: "30d"
