global:
  environment: development

gateway:
  name: api-gateway
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000

userService:
  name: user-service
  replicaCount: 1
  image:
    repository: gihaa/as-user-service
    tag: latest
  service:
    type: ClusterIP
    port: 3001

rewardService:
  name: reward-service
  replicaCount: 1
  image:
    repository: gihaa/as-reward-service
    tag: latest
  service:
    type: ClusterIP
    port: 3003

pricePredictionService:
  name: price-prediction-service
  replicaCount: 1
  image:
    repository: gihaa/as-price-prediction-service
    tag: latest
  service:
    type: ClusterIP
    port: 3002

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: gihaa/as-front-end-admin
    tag: latest
  service:
    type: LoadBalancer
    port: 80
    targetPort: 4000  

userinter:
  name: user-interaction-service
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    type: ClusterIP
    port: 3005    

chatbot:
  name: chat-bot-service
  replicaCount: 1
  image:
    repository: gihaa/as-gateway
    tag: latest
  service:
    type: ClusterIP
    port: 3007    

database:
  user: "avnadmin"
  password: "AVNS_lP0uW9A3_MC4As3h-NL"
  host: "pg-122ba407-gihansudeeparandimal-f684.g.aivencloud.com"
  port: "17670"
  name: "defaultdb"

jwt:
  secret: "your_jwt_secret"
  expiresIn: "30d"
